#!/usr/bin/env python3

import subprocess

ok_list = ['bullseye', 'bookworm', 'trixie', 'forky', 'jammy', 'focal']
warn_list = ['buster', 'bionic', 'xenial']

cmd = ["/usr/bin/lsb_release", "-ircs"]
stdout, stderr = subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE).communicate()
dist, version, codename, null = stdout.decode('utf-8').split('\n')

state: int = 0 if codename in ok_list else (1 if codename in warn_list else 2)

print (f'{state} "Distribution Info" - {dist} {version} {codename}')
